### ISSUE TITLE
Error running koha-plugin-room-reservations

### ISSUE THREAD

**Issue by abudarbeya** [bywatersolutions/koha-plugin-room-reservations#59]
Hi,

I followed all the steps in the koha-plugin-room-reservations repository, but when I running the koha-plugin-room-reservations (V. 4.02) it's not working, I use Koha 23.11 and Koha 23.05.04 all have an error.
Thanks
OPAC display this error:

I followed all the steps in the koha-plugin-room-reservations repository, 
Sorry, the requested page is not available
Error 500
This message can have the following reason(s):

An error occurred while processing your request.
What's next?
You can use the menu and links at the top of the page
You can search our catalog using the search form at the top of this page.
[Return to the catalog home page.](http://searchlib.demo.org/cgi-bin/koha/opac-main.pl)
Report issues and broken links
To report this error, please contact the Koha Administrator. [Send email](mailto:alasheh%40gmail.com).
----------------------------------------------------------------------------------------------------------------------------
I checked opac-error.log, I found this messages:
----------------------------------------------------------------------------------------------------------------------------
[Wed Dec 27 12:02:28.028627 2023] [cgi:error] [pid 9813] [client 172.17.100.100:51677] AH01215: main::getConfirmedCalendarBookingsByMonthAndYear(): DBI Exception: DBD::mysql::st execute failed: **Table 'koha_kohadev.booking_rooms' doesn't exist at** /var/lib/koha/kohadev/plugins/Koha/Plugin/Com/MarywoodUniversity/RoomReservations/opac/calendar.pl line 91: /var/lib/koha/kohadev/plugins/Koha/Plugin/Com/MarywoodUniversity/RoomReservations/opac/calendar.pl, referer: http://kohadev.demo.org/cgi-bin/koha/opac-user.pl?has-search-query=
[Wed Dec 27 12:02:28.066030 2023] [cgi:error] [pid 9813] [client 172.17.100.100:51677] End of script output before headers: calendar.pl, referer: http://kohadev.demo.org/cgi-bin/koha/opac-user.pl?has-search-query=

**Comment by schnydszch** [comment]
Hi! Experience also the same with 23.11. It seems the database tables are not created as per error in opac-error.log.

**Comment by kylemhall** [comment]
This issue should be fixed in v4.0.3, which was released just yesterday!

**Comment by schnydszch** [comment]
Hi! I uninstalled the plugin, reinstalled. Installed 4.0.2 first then 4.0.3. Rebooted the server. And then lastly, upon checking the error which tells me, it is missing 'bookings, booking_rooms tables error. I checked the tables, I am actually getting a prepended tables (e.g. bws_rr_booking, bws_rr_booking_rooms). When I renamed the tables to booking and booking_rooms, /booking page which shows a calendar is now working.

**Comment by schnydszch** [comment]
Okay, so when I changed the table names, the OPAC page (/booking) works. However, the admin panel part does not work (getting Error 505). Upon checking the log, I am getting errors on tables "bws_rr_booking", etc.

**Comment by kylemhall** [comment]
Please try v4.0.4 to see if that fixes the issue!

**Comment by schnydszch** [comment]
Tried this in another instance. Getting error in OPAC: Table 'koha_instancename.booking_rooms' doesn't exist. Looking at the database table, it is bws_rr_tablename. Renaming bws_rr_tablename to tablename will resolve the issue.

**Comment by schnydszch** [comment]
It seems that opac.pl needs adjusting to the tables so that OPAC won't get Error 500:
my $rooms_table = 'booking_rooms';
my $bookings_table = 'bookings';
my $equipment_table = 'booking_equipment';
my $roomequipment_table = 'booking_room_equipment';

**Comment by schnydszch** [comment]
Renamed the tables so OPAC won't break. However, admin panel will also break since the table names are different. :)

**Comment by abudarbeya** [comment]
HI, 
I want to make a reservation available only within library opening hours.
Opening Hours: Sunday-Thursday From 8:30 To 15:30
Thanks.
